# 查看所有配置:https://gohugobrasil.netlify.app/getting-started/configuration/#toml-configuration
baseURL = "https://it-boyer.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "习七"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "even"
enableGitInfo = true # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。
contentDir = "content"
publishdir = "public"
staticdir = "static"
ignoreFiles = [ "\\.git"]
# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
# https://gohugobrasil.netlify.app/content-management/syntax-highlighting/#configure-syntax-hightlighter
# linenos:table inline
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsStyle = "rrt"
pygmentsCodefencesGuessSyntax = true


hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10                                              # 首页每页显示的文章数
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

disablePathToLower = true
# 制定RSS最大条数 0:返回全部 特殊符合：~^H~，需要清理。
rssLimit = 30

# todo-css 无效果问题解决 ：https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[author]                  # essential                     # 必需
name = "iTBoyer"
email = "itboyer@qq.com"


# 添加作者信息:https://www.netlify.com/blog/2018/07/24/hugo-tips-how-to-create-author-pages/
[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[sitemap]                 # essential                     # 必需
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[[menu.main]]
name = "主页"
weight = 1          # 权重 控制显示次序
identifier = "home"
url = "/"
[[menu.main]]
name = "归档"
weight = 20
identifier = "archives"
url = "/post/"
[[menu.main]]
name = "标签"
weight = 30
identifier = "tags"
url = "/tags/"
[[menu.main]]
name = "分类"
weight = 40
identifier = "categories"
url = "/categories/"

[[menu.main]]
name = "周报"
weight = 43
identifier = "week"
url = "/categories/周报/"

[[menu.main]]
name = "文档"
weight = 50
identifier = "iDocs"
url = "/iDocs/"

[[menu.main]]             # config your menu              # 配置目录
name = "关于"
weight = 0
identifier = "ime0"
url = "/authors/itboyer/"


[[menu.main]]
name = "认识我"
weight = 0
identifier = "resume"
url = "/resume"



[params]
version = "4.x"           # Used to give a friendly message when you have an incompatible update
debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

since = "2017"            # Site creation time          # 站点建立时间
# use public git repo url to link lastmod git commit, enableGitInfo should be true.
# 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
gitRepo = "iNotes"

# site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
logoTitle = "习七"        # default: the title value    # 默认值: 上面设置的title值
keywords = ["swift","iOS","积极主动","以终为始","要事第一","效能平衡"]
description = "不物喜,不己悲;善假物,易参行."

# paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
archivePaginate = 20

# show 'xx Posts In Total' in archive page ?            # 是否在归档页显示文章的总数
showArchiveCount = true

# The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
dateFormatToUse = "2006-01-02"

# show word count and read time ?                       # 是否显示字数统计与阅读时间
moreMeta = true

# Syntax highlighting by highlight.js
# highlightInClient = true

# 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
# Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
toc = true                                                                            # 是否开启目录
autoCollapseToc =  true  # Auto expand and collapse toc                              # 目录自动展开/折叠
fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）
# algolia
algolia = false  # 是否启用algolia
  index = "qikqiak-blog"
  key = $HUGO_ALGOLIA_KEY
  appID = $HUGO_ALGOLIA_APPID
  
# mathjax
mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
mathjaxEnableSingleDollar = false                                                     # 是否使用 $...$ 即可進行inline latex渲染
mathjaxEnableAutoNumber = false                                                       # 是否使用公式自动编号
mathjaxUseLocalFiles = false  # You should install mathjax in `yout-site/static/lib/mathjax`

postMetaInFooter = true   # contain author, lastMod, markdown link, license           # 包含作者，上次修改时间，markdown链接，许可信息
linkToMarkDown = true     # Only effective when hugo will output .md files.           # 链接到markdown原始文件（仅当允许hugo生成markdown文件时有效）
contentCopyright = ''     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

changyanAppid = ""        # Changyan app id             # 畅言
changyanAppkey = ""       # Changyan app key

livereUID = ""            # LiveRe UID                  # 来必力

baiduPush = false        # baidu push                  # 百度
baiduAnalytics = ""      # Baidu Analytics
baiduVerification = ""   # Baidu Verification
googleVerification = ""  # Google Verification         # 谷歌

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
customCSS = ["search.css","copy-to-clipboard.css","todo.css"]
customJS = []

uglyURLs = false          # please keep same with uglyurls setting

[params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
enable = true
jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

# Display a message at the beginning of an article to warn the readers that it's content may be outdated.
# 在文章开头显示提示信息，提醒读者文章内容可能过时。
[params.outdatedInfoWarning]
enable = true
hint = 30               # Display hint if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示提醒
warn = 180              # Display warning if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示警告

[params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
#owner = "it-boyer"              # Your GitHub ID
#repo = "it-boyer.github.io"               # The repo to store comments
#clientId = ""           # Your client ID
#clientSecret = ""       # Your client secret

[params.utterances]       # https://utteranc.es/
owner = ""              # Your GitHub ID
repo = ""               # The repo to store comments

[params.gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
owner = "it-boyer"              # Your GitHub ID
repo = "it-boyer.github.io"               # The repo to store comments
clientId = $HUGO_GITALK_CLIENTID           # Your client ID
clientSecret = $HUGO_GITALK_CLIENTSECRET       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
enable = false
appId = '你的appId'
appKey = '你的appKey'
notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
verify = false # Verification code
avatar = 'mm'
placeholder = '说点什么吧...'
visitor = false

[params.flowchartDiagrams]# see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
enable = false
options = ""

[params.sequenceDiagrams] # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
enable = false
options = ""            # default: "{theme: 'simple'}"

[params.busuanzi]         # count web traffic by busuanzi                             # 是否使用不蒜子统计站点访问量
enable = true
siteUV = true
sitePV = true
pagePV = true

[params.reward]                                         # 文章打赏
enable = true
wechat = "/img/reward/weixin.jpg"           # 微信二维码
alipay = "/img/reward/zhifubao.jpg"           # 支付宝二维码

[params.social]                                         # 社交链接
a-email = "mailto:iTBoyer@qq.com"
g-github = "https://github.com/it-boyer"
h-weibo = "http://weibo.com/1791281385"
i-zhihu = "http://www.zhihu.com/people/boyers"
j-douban = "http://douban.com/people/boyers"
o-bilibili = "https://space.bilibili.com/67083417"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.googleAnalytics]
anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
[privacy.youtube]
privacyEnhanced = true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
[mediaTypes]
 [mediaTypes."text/plain"]
   suffixes = ["md"]

[outputFormats.MarkDown]
 mediaType = "text/plain"
 isPlainText = true
 isHTML = false
#
[outputs]
  home = ["HTML", "RSS", "JSON"]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
